### ISSUE TITLE
Cannot reset control value on form.reset()

### ISSUE THREAD

**Issue by punit-singh999** [tanansatpal/ngx-mat-intl-tel-input#20] opened 2019-09-21 05:51 UTC
the control not getting reset after calling form.reset().  
is there way to clear value from the control and reset it?

**Comment by tanansatpal** [comment] 2019-09-22 14:31
Hi @punit-singh999 , the issue is fixed in the latest version. Please update to the latest version.

**Closed by tanansatpal** 2019-09-22 14:31 UTC

**Comment by shivam0dot7** [comment] 2020-08-10 14:44
I am facing the same issue again in version 3.1.0 (latest). Could you please let me know the solution or some workaround to it. Working on a high priority task!
